
import React, { useState } from "react";
import { Globe, Search, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useNavigate } from "react-router-dom";

function WorldMapSection() {
    const navigate = useNavigate();
    const [searchTerm, setSearchTerm] = useState('');

    const continentData = [
        { name: "North America", institutions: "7400+", color: "bg-orange-500" },
        { name: "Europe", institutions: "2100+", color: "bg-orange-500" },
        { name: "Asia", institutions: "2250+", color: "bg-orange-500" },
        { name: "Oceania", institutions: "350+", color: "bg-orange-500" },
        { name: "South America", institutions: "450+", color: "bg-orange-500" },
        { name: "Africa", institutions: "125+", color: "bg-orange-500" },
    ];

    const handleSearchSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (searchTerm.trim()) {
            navigate(`/institution-search?q=${encodeURIComponent(searchTerm.trim())}`);
        } else {
            navigate('/institution-search');
        }
    };

    return (
        <div className="mb-16">
            {/* World Map Section */}
            <div className="bg-white/80 backdrop-blur-sm rounded-3xl p-8 shadow-xl border border-slate-200/50">
                <div className="text-center mb-8">
                    <h2 className="text-3xl font-bold text-slate-800 mb-4 flex items-center justify-center">
                        <Globe className="mr-3 h-8 w-8 text-blue-600" />
                        A Whole World of Opportunity
                    </h2>
                    <p className="text-xl text-slate-600">
                        See where TOEFL iBT is accepted!
                    </p>
                </div>

                {/* World Map Visualization */}
                <div className="relative bg-gradient-to-br from-blue-50 to-purple-50 rounded-2xl p-8 mb-8">
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {continentData.map((continent, index) => (
                            <div key={index} className="relative">
                                <div className="bg-white rounded-xl p-6 shadow-lg border border-slate-200 hover:shadow-xl transition-shadow duration-200">
                                    <div
                                        className={`w-full h-3 ${continent.color} rounded-full mb-4`}
                                    ></div>
                                    <h3 className="text-xl font-bold text-slate-800 mb-2">
                                        {continent.name}
                                    </h3>
                                    <p className="text-2xl font-bold text-orange-600 mb-1">
                                        {continent.institutions}
                                    </p>
                                    <p className="text-slate-600 text-sm">Institutions</p>
                                </div>
                            </div>
                        ))}
                    </div>

                    {/* Total Statistics */}
                    <div className="text-center mt-8 p-6 bg-white rounded-xl shadow-lg border border-slate-200">
                        <h3 className="text-2xl font-bold text-slate-800 mb-2">
                            Total Global Acceptance
                        </h3>
                        <div className="flex flex-col sm:flex-row justify-center items-center gap-8">
                            <div className="text-center">
                                <div className="text-4xl font-bold text-blue-600">12,000+</div>
                                <div className="text-slate-600">Institutions</div>
                            </div>
                            <div className="text-center">
                                <div className="text-4xl font-bold text-purple-600">160+</div>
                                <div className="text-slate-600">Countries</div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Search Section */}
                <div className="text-center bg-gradient-to-r from-blue-50 to-purple-50 rounded-2xl p-8">
                    <h3 className="text-2xl font-bold text-slate-800 mb-4">
                        Find Your Institution
                    </h3>
                    <p className="text-slate-600 mb-6">
                        Search to check if your university accepts TOEFL iBT. This answer is generated by an AI model (OpenAI GPT) based on publicly available information.
                    </p>

                    <form onSubmit={handleSearchSubmit} className="max-w-md mx-auto">
                        <div className="flex gap-3">
                            <div className="relative flex-1">
                                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-5 w-5" />
                                <Input
                                    type="text"
                                    placeholder="Search university..."
                                    value={searchTerm}
                                    onChange={(e) => setSearchTerm(e.target.value)}
                                    className="pl-10 pr-4 py-3 text-lg border-2 border-gray-200 focus:border-blue-500 rounded-xl"
                                />
                            </div>
                            <Button
                                type="submit"
                                className="bg-blue-600 hover:bg-blue-700 text-white rounded-xl px-6 py-3 group"
                            >
                                Search
                                <ArrowRight className="ml-2 h-5 w-5 transition-transform group-hover:translate-x-1" />
                            </Button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
}

export default WorldMapSection;
