
-- Insert Test 7 if it doesn't exist
INSERT INTO public.toefl_tests (id, title, difficulty, duration, description) 
VALUES (7, 'TOEFL Practice Test 7', 'Intermediate', '2 hours', 'Complete TOEFL practice test with all four sections')
ON CONFLICT (id) DO NOTHING;

-- Insert listening passages for Test 7
INSERT INTO public.test_passages (test_id, section_type, title, content, order_number, audio_duration, audio_type, audio_url) VALUES 

-- Test 7 Lecture 1 (Biology)
(7, 'listening', 'Photosynthesis and Its Importance', 'Good morning, everyone. Today we''re going to delve into the process of photosynthesis, a fundamental biological mechanism that sustains life on Earth.

Photosynthesis is the process by which green plants, algae, and some bacteria convert light energy from the sun into chemical energy stored in glucose, a type of sugar. This process not only provides energy for the organisms that perform it but also produces oxygen, which is essential for most life forms.

The process takes place mainly in the chloroplasts of plant cells. Chloroplasts contain chlorophyll, a pigment that absorbs light, primarily in the blue and red wavelengths, while reflecting green, which is why plants appear green to us.

Excellent question. Chlorophyll absorbs sunlight and converts it into chemical energy through a series of reactions. This energy is then used to transform carbon dioxide from the air and water from the soil into glucose and oxygen.

Photosynthesis occurs in two main stages: the light-dependent reactions and the light-independent reactions, also called the Calvin cycle. During the light-dependent stage, light energy splits water molecules into oxygen, protons, and electrons. Oxygen is released as a byproduct into the atmosphere.

In the Calvin cycle, the plant uses the energy produced during the first stage to fix carbon dioxide, converting it into glucose. This glucose can be used immediately for energy or stored as starch for later use.

This process is vital not only because it produces oxygen but also because it forms the base of the food chain. Herbivores consume plants for energy, and carnivores, in turn, consume herbivores, passing energy through the ecosystem.

The rate of photosynthesis is influenced by several factors, including light intensity, carbon dioxide concentration, and temperature. For instance, at low light levels, photosynthesis slows because there isn''t enough energy to drive the reactions.

Good question. High temperatures can damage the enzymes involved in photosynthesis, reducing the plant''s efficiency. Extreme heat can also cause plants to close their stomata—the pores on leaves—to reduce water loss, which limits carbon dioxide intake.

Photosynthesis also plays a critical role in regulating the Earth''s atmosphere. By absorbing carbon dioxide, plants help reduce greenhouse gases and combat global warming.

In recent decades, scientists have explored ways to increase photosynthesis efficiency to improve crop yields and address food shortages. Genetic engineering and selective breeding have shown promise in developing plants that grow faster or withstand harsh environmental conditions.

In aquatic environments, photosynthesis is performed by algae and cyanobacteria, which produce a significant portion of the oxygen we breathe. These organisms are the foundation of many marine food webs.

No, they aren''t. Some plants, like those in hot, dry climates, have developed special adaptations called C4 or CAM photosynthesis to conserve water. These processes are more efficient under certain conditions and help plants survive in harsh environments.

To sum up, photosynthesis is a complex but vital process that sustains life by producing energy and oxygen. Its efficiency is influenced by environmental factors, and understanding it helps us tackle ecological and agricultural challenges.

Next lecture, we will discuss cellular respiration, the process by which cells convert glucose back into usable energy.', 1, 420, 'lecture', 'listening/t7l1.mp3'),

-- Test 7 Lecture 2 (Geology)
(7, 'listening', 'Plate Tectonics and Earthquakes', 'Hello everyone. Today''s lecture is about plate tectonics and how it relates to earthquakes.

Plate tectonics is the theory that Earth''s outer shell, the lithosphere, is divided into several large and small plates that float on the semi-fluid asthenosphere beneath them. These plates constantly move due to forces generated by heat deep inside the Earth.

There are three main types of plate boundaries: divergent, convergent, and transform. At divergent boundaries, plates move apart, allowing magma to rise and create new crust. This process forms mid-ocean ridges, like the Mid-Atlantic Ridge.

At convergent boundaries, plates move toward each other. Depending on the types of plates involved, this can cause one plate to slide beneath another in a process called subduction, leading to the formation of mountain ranges, volcanic activity, and deep ocean trenches.

Transform boundaries occur where plates slide past each other horizontally. The San Andreas Fault in California is a famous example of a transform boundary.

Earthquakes occur when the stress along these plate boundaries overcomes friction, causing the plates to suddenly slip and release energy as seismic waves.

The point inside the Earth where the earthquake originates is called the focus, while the point on the surface directly above it is the epicenter.

We use the Richter scale and the moment magnitude scale to quantify earthquake magnitude, which indicates the energy released. The Richter scale is older and based on seismic wave amplitude, while the moment magnitude scale is now preferred for its accuracy across different sizes and distances.

The intensity of shaking experienced at different locations is measured by the Modified Mercalli Intensity scale, which is based on observed effects.

Earthquake hazards include ground shaking, surface rupture, landslides, and tsunamis. The latter occur when underwater earthquakes displace large volumes of water, generating powerful waves.

Scientists use seismographs to detect and record seismic waves, helping to locate earthquakes and study Earth''s interior.

Understanding plate tectonics and earthquake mechanisms helps engineers design buildings and infrastructure that are more resistant to seismic events.

In recent years, early warning systems have been developed to provide seconds to minutes of advance notice, which can save lives by allowing people to take protective actions.

Currently, precise prediction is not possible. Scientists can assess earthquake probabilities over long periods but cannot forecast the exact time and location.

In conclusion, plate tectonics explains much about Earth''s geological activity, including the causes of earthquakes. Studying these processes is essential for minimizing risks and protecting communities.

Next week, we will explore volcanic activity and its impact on the environment.', 2, 415, 'lecture', 'listening/t7l2.mp3'),

-- Test 7 Lecture 3 (Economics)
(7, 'listening', 'Supply and Demand', 'Good afternoon. Today, we''ll discuss the fundamental concepts of supply and demand, which form the basis of market economics. Supply refers to how much of a good or service producers are willing and able to sell at various prices, while demand represents how much consumers are willing and able to buy.

The law of demand states that, all else equal, when prices rise, the quantity demanded decreases, and when prices fall, demand increases. This inverse relationship is shown graphically by a downward-sloping demand curve. However, demand is influenced by many factors beyond price.

Great question. Factors include consumer income, tastes and preferences, prices of related goods, expectations about the future, and the number of buyers. For example, if consumers expect prices to rise in the future, current demand might increase as people buy ahead. Similarly, if the price of a substitute good falls, demand for the original good may decrease.

On the supply side, producers generally supply more of a good when the price increases, because higher prices mean greater potential profits. This positive relationship is represented by an upward-sloping supply curve. But supply is also influenced by other factors.

These include production costs, technological advances, taxes and subsidies, expectations about future prices, and the number of sellers in the market. For instance, if technology improves, it might become cheaper to produce a good, increasing supply at every price.

When supply and demand meet, they determine the market equilibrium price and quantity — the point where the quantity supplied equals the quantity demanded. At this price, the market clears, meaning there''s neither a surplus nor a shortage.

If the market price is above equilibrium, a surplus occurs, leading sellers to lower prices to sell excess goods. Conversely, if the price is below equilibrium, a shortage develops, pushing prices up as buyers compete for limited supply.

Market forces tend to push prices toward equilibrium naturally, adjusting to changes in supply or demand. For example, if a new fashion trend increases demand for a product, prices may rise until supply increases to meet that demand.

Shifts in supply or demand curves cause new equilibrium points. For example, government policies such as subsidies can lower production costs, increasing supply. On the other hand, a rise in raw material prices can reduce supply.

Price controls are another important topic. Governments sometimes impose price floors or ceilings. A price floor, like a minimum wage, sets a legal minimum price, which can lead to surpluses if set above equilibrium. A price ceiling, like rent control, caps prices below equilibrium, potentially causing shortages.

Understanding these dynamics is crucial for policymakers and businesses, as interventions can have unintended consequences if market forces aren''t carefully considered.

In summary, supply and demand explain how prices and quantities are determined in markets and how they respond to changes. These concepts are fundamental for analyzing economic behavior and making informed decisions.

Next session, we''ll explore market failures and the role of government intervention, including externalities and public goods.', 3, 425, 'lecture', 'listening/t7l3.mp3'),

-- Test 7 Conversation 1 (Light Pollution Research)
(7, 'listening', 'Light Pollution Research Proposal', 'Hi Professor, thanks for meeting me. Of course. What''s up? I''m drafting a proposal on reducing light pollution in campus housing. Great topic. What''s your first action plan? Conduct light measurements in dorm courtyard areas. Good. What tools will you use? A light meter app and handheld lux sensors. Reliable. Will you include student surveys? Yes—to assess awareness and attitudes. Excellent. What research question are you asking? Can shielding and reduced light intensity improve wildlife and sleep quality? Strong question. How will you test human effects? Survey residents before and after light adjustments. Good design. Any hypothesis? Yes: residents near shielded lighting report better sleep. Clear and measurable. Do I need a control site? Yes—an unmodified courtyard as comparison. Will lighting be changed in winter? Best in spring to avoid seasonal sleep variability. What about sharing results? Present at student sustainability forum. That''d be great. Anything else? No, thanks. Good luck with your project!', 4, 190, 'conversation', 'listening/t7c1.mp3'),

-- Test 7 Conversation 2 (Biomimicry Workshop)
(7, 'listening', 'Biomimicry Workshop Planning', 'Good morning, Professor. Good morning. What can I help with? I''m organizing a campus workshop on biomimicry. Excellent. What''s the theme and audience? High school students interested in science and design. Good target audience. What activities are being planned? Hands-on demos like gecko tape and paper bee hive structures. Interactive! How many participants expected? About 30 to 40 students. Do you have supplies and budget yet? I''ve drafted a budget for materials and lab bookings. Have you arranged lab space? Yes—chemistry room next Friday afternoon. Have you prepared safety guidelines? Yes—we''ll include safety briefings and supervision. Smart. What''s the schedule? Welcome talk, demo session, Q&A, then feedback forms. Sounds structured. Will you assess learning? Yes—pre and post simple quizzes. Good evaluation method. Will there be refreshments? Keep them simple—water and snacks. Noted. Have you promoted it? Flyers, social media post, and email lists. Good outreach. What about certificates of attendance? Nice idea—students appreciate that. I''ll arrange printing. Anything else? No, thanks for your help! You''re welcome—hope it goes well.', 5, 210, 'conversation', 'listening/t7c2.mp3');

-- Insert listening questions for Test 7
INSERT INTO public.test_questions (test_id, passage_id, section_type, question_number, question_type, question_text, options, correct_answer) VALUES 

-- Test 7 Lecture 1 Questions (Biology - Photosynthesis)
(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Photosynthesis and Its Importance' AND section_type = 'listening'), 'listening', 1, 'Gist-Content', 'What is the lecture mainly about?', '["The role of chlorophyll in plants", "The process and significance of photosynthesis", "Different types of plants and algae", "The effects of temperature on plants"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Photosynthesis and Its Importance' AND section_type = 'listening'), 'listening', 2, 'Detail', 'What happens during the light-dependent reactions of photosynthesis?', '["Carbon dioxide is converted into glucose", "Water molecules are split and oxygen is released", "Glucose is stored as starch", "Chlorophyll is produced"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Photosynthesis and Its Importance' AND section_type = 'listening'), 'listening', 3, 'Function', 'Why does the professor mention stomata closing in high temperatures?', '["To explain how plants prevent water loss", "To describe how plants absorb more carbon dioxide", "To illustrate how photosynthesis speeds up", "To discuss plant reproduction"]', '0'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Photosynthesis and Its Importance' AND section_type = 'listening'), 'listening', 4, 'Detail', 'Which organisms perform photosynthesis in aquatic environments?', '["Fish and amphibians", "Algae and cyanobacteria", "Coral and shellfish", "Seagrasses only"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Photosynthesis and Its Importance' AND section_type = 'listening'), 'listening', 5, 'Inference', 'What can be inferred about C4 and CAM plants?', '["They are less efficient in photosynthesis", "They have adapted to conserve water in harsh climates", "They do not produce oxygen", "They grow only underwater"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Photosynthesis and Its Importance' AND section_type = 'listening'), 'listening', 6, 'Attitude', 'What is the professor attitude toward scientific research on photosynthesis?', '["Skeptical", "Supportive and optimistic", "Indifferent", "Critical"]', '1'),

-- Test 7 Lecture 2 Questions (Geology - Plate Tectonics and Earthquakes)
(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Plate Tectonics and Earthquakes' AND section_type = 'listening'), 'listening', 7, 'Gist-Content', 'What is the main topic of the lecture?', '["The history of earthquakes worldwide", "Plate tectonics and its relation to earthquakes", "The process of mountain building only", "The development of seismograph instruments"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Plate Tectonics and Earthquakes' AND section_type = 'listening'), 'listening', 8, 'Detail', 'What occurs at divergent plate boundaries?', '["Plates slide past each other", "Plates move apart and new crust forms", "One plate slides beneath another", "Earthquakes never happen"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Plate Tectonics and Earthquakes' AND section_type = 'listening'), 'listening', 9, 'Function', 'Why does the professor discuss the San Andreas Fault?', '["To give an example of a transform boundary", "To explain volcanic activity", "To describe ocean trenches", "To discuss the Richter scale"]', '0'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Plate Tectonics and Earthquakes' AND section_type = 'listening'), 'listening', 10, 'Detail', 'What does the Richter scale measure?', '["The intensity of shaking experienced", "The energy released by an earthquake", "The depth of the earthquake focus", "The length of a fault line"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Plate Tectonics and Earthquakes' AND section_type = 'listening'), 'listening', 11, 'Inference', 'What can be inferred about earthquake prediction?', '["Exact predictions are currently impossible", "Earthquakes can be forecasted days in advance", "Prediction technology is highly accurate", "Earthquakes only occur in California"]', '0'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Plate Tectonics and Earthquakes' AND section_type = 'listening'), 'listening', 12, 'Attitude', 'What is the professor attitude toward current earthquake prediction methods?', '["Frustrated with limitations", "Confident in precise forecasts", "Neutral and factual", "Disbelieving that prediction is possible"]', '2'),

-- Test 7 Lecture 3 Questions (Economics - Supply and Demand)
(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Supply and Demand' AND section_type = 'listening'), 'listening', 13, 'Gist-Content', 'What is the lecture mainly about?', '["How markets fail and government intervention", "Basic principles of supply and demand in markets", "The history of economic thought", "Price controls only"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Supply and Demand' AND section_type = 'listening'), 'listening', 14, 'Detail', 'According to the professor, what happens when prices rise?', '["Quantity demanded increases", "Quantity demanded decreases", "Supply decreases", "Demand stays the same"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Supply and Demand' AND section_type = 'listening'), 'listening', 15, 'Function', 'Why does the professor mention consumers expectations about future prices?', '["To explain how expectations affect demand", "To describe supply shifts", "To illustrate government policy", "To discuss price floors"]', '0'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Supply and Demand' AND section_type = 'listening'), 'listening', 16, 'Detail', 'What is an example of a factor that can shift the supply curve?', '["Change in consumer income", "Technological improvement", "Change in taste", "Number of buyers"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Supply and Demand' AND section_type = 'listening'), 'listening', 17, 'Inference', 'What can be inferred about price floors and ceilings?', '["They always improve market efficiency", "They can cause surpluses or shortages", "They are rarely used by governments", "They eliminate the need for supply and demand"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Supply and Demand' AND section_type = 'listening'), 'listening', 18, 'Attitude', 'What is the professor attitude toward understanding supply and demand?', '["It is crucial for informed decision-making", "It is only important for economists", "It is too complex for most people", "It is less relevant today"]', '0'),

-- Test 7 Conversation 1 Questions (Light Pollution Research)
(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Light Pollution Research Proposal' AND section_type = 'listening'), 'listening', 19, 'Gist-Purpose', 'Why is the student meeting the professor?', '["To ask for funding", "To discuss a light pollution research proposal", "To request dorm repair", "To change courses"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Light Pollution Research Proposal' AND section_type = 'listening'), 'listening', 20, 'Detail', 'What tools will the student use for measuring light?', '["Lux sensors and app", "Binoculars", "GPS tracker", "Weather station"]', '0'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Light Pollution Research Proposal' AND section_type = 'listening'), 'listening', 21, 'Attitude', 'What is the professor attitude toward the proposal?', '["Dismissive", "Supportive", "Neutral", "Skeptical"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Light Pollution Research Proposal' AND section_type = 'listening'), 'listening', 22, 'Function', 'What does the professor mean by present at student sustainability forum?', '["Attend and share findings publicly", "Host a concert", "Publish a diary", "Join a club"]', '0'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Light Pollution Research Proposal' AND section_type = 'listening'), 'listening', 23, 'Organization', 'Why does the professor suggest a control site?', '["To have a basis for comparison", "To test random locations", "To avoid surveys", "To limit data"]', '0'),

-- Test 7 Conversation 2 Questions (Biomimicry Workshop)
(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Biomimicry Workshop Planning' AND section_type = 'listening'), 'listening', 24, 'Gist-Purpose', 'Why is the student meeting the professor?', '["To request a recommendation", "To plan a workshop on biomimicry", "To complain about labs", "To find lab partners"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Biomimicry Workshop Planning' AND section_type = 'listening'), 'listening', 25, 'Detail', 'What activities are planned?', '["A lecture only", "Gecko tape and paper hive demos", "Field trip", "Movie screening"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Biomimicry Workshop Planning' AND section_type = 'listening'), 'listening', 26, 'Attitude', 'What is the professor attitude toward the event?', '["Dismissive", "Approving and helpful", "Neutral", "Alarmed"]', '1'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Biomimicry Workshop Planning' AND section_type = 'listening'), 'listening', 27, 'Function', 'What does the professor mean by pre and post simple quizzes?', '["To test student knowledge before and after the workshop", "To scare participants", "To add difficulty", "To compare participants"]', '0'),

(7, (SELECT id FROM public.test_passages WHERE test_id = 7 AND title = 'Biomimicry Workshop Planning' AND section_type = 'listening'), 'listening', 28, 'Organization', 'Why suggest certificates of attendance?', '["To add value for participants", "To complicate logistics", "To replace feedback forms", "To promote snacks"]', '0');
