
-- Insert the second passage (Trade Along the Silk Road) into test_passages table
INSERT INTO public.test_passages (test_id, section_type, title, content, order_number) VALUES 
('00000000-0000-0000-0000-000000000001', 'reading', 'Trade Along the Silk Road', '[1] The Silk Road was not a single road but a vast network of trade routes that connected China with the Mediterranean world. Spanning over 6,000 kilometers, this network enabled the exchange of goods, ideas, technologies, and cultures for more than a thousand years. The term "Silk Road" was coined in the 19th century by the German geographer Ferdinand von Richthofen, referring to the lucrative trade in silk that was carried out along these routes. Although silk was a major commodity, traders also dealt in spices, glassware, paper, precious metals, and other goods. The Silk Road reached its height during the Tang and Yuan dynasties in China, facilitating interaction between East and West.

[2] One of the critical features of Silk Road commerce was its relay-trade nature. Rather than having goods transported by a single trader along the entire route, merchandise often passed through the hands of many different traders and middlemen. For example, Chinese silk might be traded to Central Asian merchants, who then exchanged it with Persian or Arab traders, eventually reaching the markets of Rome or Constantinople. This system allowed local traders to specialize in certain segments of the route, making the entire operation more efficient and adaptable to political or environmental changes.

[3] The Silk Road also facilitated the transmission of culture and religion. As merchants and pilgrims moved across vast distances, they carried with them not just goods but also stories, beliefs, and technologies. Buddhism, for instance, spread from India to China largely through the efforts of monks traveling along these trade routes. Similarly, artistic styles, architectural motifs, and even culinary practices were shared and adapted by the various civilizations connected by the Silk Road.

[4] Political stability was crucial for the prosperity of the Silk Road. When strong empires such as the Tang dynasty in China or the Mongol Empire under Genghis Khan provided security, trade flourished. These empires maintained roads, suppressed banditry, and established relay stations, which ensured that goods and people could move with relative safety. In contrast, periods of fragmentation or warfare often disrupted trade, causing some routes to become impassable or unsafe. Traders would then divert their goods through alternate paths or switch to maritime trade.

[5] While the overland Silk Road was vital for centuries, maritime trade routes eventually began to rival and, in some areas, surpass it in importance. The rise of naval technology and the exploration of sea routes by Arab, Indian, and later European merchants allowed for the transport of larger quantities of goods at a lower cost. By the 15th century, the maritime Silk Road, connecting China through the South China Sea and Indian Ocean to Africa and Europe, became the dominant channel for trade.

[6] Despite its decline in the early modern period, the Silk Road had a lasting impact on world history. It was instrumental in shaping early globalization by linking distant regions and fostering intercultural exchange. Many of the ideas, inventions, and commodities that moved along the Silk Road influenced societies far from their origin. Today, the legacy of the Silk Road is remembered not only in museums and historical texts but also in modern initiatives aimed at reviving trade connectivity across Eurasia.', 2);
