
-- Insert questions for Test 1 - Reading Section

-- Questions 1-10 for first passage (Cambrian Explosion)
INSERT INTO public.test_questions (test_id, passage_id, section_type, question_number, question_type, question_text, options, correct_answer) VALUES 
('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'The Cambrian Explosion'), 'reading', 1, 'Factual Information', 'According to paragraph 1, which of the following was a characteristic of the Cambrian Explosion?', '["It occurred over several billion years.", "It involved the appearance of most single-celled organisms.", "It led to the emergence of most major animal groups.", "It resulted in the extinction of earlier species."]', '2'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'The Cambrian Explosion'), 'reading', 2, 'Negative Factual Information', 'According to paragraph 2, all of the following are proposed causes of the Cambrian Explosion EXCEPT:', '["a rise in atmospheric oxygen", "the development of advanced nervous systems", "ecological interactions like predator-prey relationships", "environmental changes"]', '1'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'The Cambrian Explosion'), 'reading', 3, 'Vocabulary', 'The word "catalyst" in paragraph 2 is closest in meaning to:', '["alternative", "example", "cause", "barrier"]', '2'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'The Cambrian Explosion'), 'reading', 4, 'Vocabulary', 'The phrase "taxonomic groups" in paragraph 4 refers to:', '["regions where fossils are found", "categories used to classify organisms", "geological periods", "extinct species"]', '1'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'The Cambrian Explosion'), 'reading', 5, 'Inference', 'What can be inferred from paragraph 3 about Hox genes?', '["They are found only in animals from the Cambrian period.", "They allowed for a greater diversity of body structures.", "They prevented earlier organisms from developing.", "They evolved after the Cambrian Explosion."]', '1'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'The Cambrian Explosion'), 'reading', 6, 'Factual Information', 'According to paragraph 4, why are the Burgess Shale and Chengjiang fossil sites important?', '["They contain the oldest known fossils on Earth.", "They provide detailed fossil records of soft-bodied organisms.", "They show the first examples of plant life.", "They were formed by volcanic activity."]', '1'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'The Cambrian Explosion'), 'reading', 7, 'Sentence Simplification', 'Which of the following best expresses the essential information in the highlighted sentence from paragraph 5?', '["The explosion seemed sudden because evolution was faster in the Cambrian.", "Some believe the rapid evolution during the Cambrian was due to better preservation of fossils.", "Improved fossil preservation may explain why the explosion appears sudden, even if evolution wasn''t unusually fast.", "Fossils from earlier periods were more numerous than Cambrian fossils."]', '2'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'The Cambrian Explosion'), 'reading', 8, 'Rhetorical Purpose', 'Why does the author mention bizarre fossils in paragraph 4?', '["To argue that the Cambrian Explosion caused mass extinction", "To show that not all early animals fit into modern classifications", "To demonstrate the poor preservation of early fossils", "To suggest that all life forms today are descended from them"]', '1'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'The Cambrian Explosion'), 'reading', 9, 'Insert Text', 'Where would the following sentence best fit in paragraph 1?', '["After the first sentence", "After the second sentence", "After the third sentence", "At the end of the paragraph"]', '2'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'The Cambrian Explosion'), 'reading', 10, 'Prose Summary', 'An introductory sentence for a brief summary of the passage is provided below. Complete the summary by selecting the THREE answer choices that express the most important ideas in the passage.', '["The development of Hox genes may have enabled the evolution of complex body plans.", "Some fossils from the Cambrian period remain difficult to classify.", "The Cambrian Explosion resulted in the extinction of earlier simple organisms.", "Fossil sites like the Burgess Shale help scientists understand early animal life.", "The Cambrian Explosion likely occurred because of a combination of genetic, ecological, and environmental factors.", "The Earth''s magnetic field changed significantly during the Cambrian period."]', '[0, 3, 4]');

-- Questions 11-20 for second passage (Silk Road)
INSERT INTO public.test_questions (test_id, passage_id, section_type, question_number, question_type, question_text, options, correct_answer) VALUES 
('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'Trade Along the Silk Road'), 'reading', 11, 'Factual Information', 'According to paragraph 1, what does the term "Silk Road" specifically refer to?', '["A single trade route between China and Europe", "A collection of trade routes named by a 19th-century geographer", "The paper trade between China and India", "The route used exclusively for transporting Chinese silk"]', '1'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'Trade Along the Silk Road'), 'reading', 12, 'Negative Factual Information', 'According to paragraph 2, all of the following are characteristics of Silk Road trade EXCEPT:', '["A single trader often traveled the entire route", "Goods passed through multiple hands", "Traders specialized in certain sections of the route", "Trade routes could shift due to political changes"]', '0'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'Trade Along the Silk Road'), 'reading', 13, 'Vocabulary', 'The word "relay" in paragraph 2 is closest in meaning to:', '["complete", "repetitive", "sequential", "occasional"]', '2'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'Trade Along the Silk Road'), 'reading', 14, 'Vocabulary', 'The word "prosperity" in paragraph 4 is closest in meaning to:', '["expansion", "wealth", "danger", "tradition"]', '1'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'Trade Along the Silk Road'), 'reading', 15, 'Inference', 'What can be inferred from paragraph 3 about cultural diffusion along the Silk Road?', '["It occurred only during times of war", "It was an accidental consequence of trade", "It helped unify Asian and European governments", "It involved the intentional spread of religions and ideas"]', '3'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'Trade Along the Silk Road'), 'reading', 16, 'Factual Information', 'According to paragraph 4, why did trade flourish under strong empires?', '["They lowered trade taxes across the empire", "They required all merchants to travel the entire route", "They offered protection and maintained infrastructure", "They discouraged maritime trade"]', '2'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'Trade Along the Silk Road'), 'reading', 17, 'Sentence Simplification', 'Which of the sentences below best expresses the essential information in the highlighted sentence from paragraph 5?', '["As trade over land declined, European merchants increased their wealth.", "Technological advances made sea travel more dangerous but efficient.", "Sea routes became preferable for moving more goods more cheaply.", "Naval technology was not used by Asian traders until later periods."]', '2'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'Trade Along the Silk Road'), 'reading', 18, 'Rhetorical Purpose', 'Why does the author mention Buddhism in paragraph 3?', '["To show how religious tolerance developed in Asia", "To illustrate how trade routes spread spiritual beliefs", "To explain the disappearance of ancient trade religions", "To argue that the Silk Road was primarily a religious path"]', '1'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'Trade Along the Silk Road'), 'reading', 19, 'Insert Text', 'Where would the following sentence best fit in paragraph 1?', '["After the first sentence", "After the second sentence", "After the third sentence", "At the end of the paragraph"]', '1'),

('00000000-0000-0000-0000-000000000001', (SELECT id FROM public.test_passages WHERE title = 'Trade Along the Silk Road'), 'reading', 20, 'Prose Summary', 'An introductory sentence for a brief summary of the passage is provided below. Complete the summary by selecting the THREE answer choices that express the most important ideas in the passage.', '["Political stability along the route encouraged economic activity and cultural exchange.", "Relay trade enabled goods to reach distant markets without long-distance travel by individual merchants.", "Paper and silk were the only goods transported along the Silk Road.", "Religious and cultural ideas moved alongside commercial goods.", "Maritime routes eventually overtook land routes in importance due to efficiency and lower costs.", "The Silk Road remained the most important trade network until the 20th century."]', '[0, 1, 3, 4]');
