
-- Insert listening passages for Test 1 (using smallint 1 for test_id)
INSERT INTO public.test_passages (test_id, section_type, title, content, order_number, audio_type, audio_duration) VALUES 
(1, 'listening', 'History Lecture: The Printing Press', 'Today, we''re going to explore one of the most significant inventions in human history—the printing press—and how it transformed societies across Europe and beyond. Before the printing press, books were produced manually, typically by scribes who copied texts by hand. This process was slow, laborious, and prone to errors, which made books rare and expensive. In medieval Europe, only monasteries, universities, and the wealthiest households had access to manuscripts. Most people were illiterate, and knowledge was largely confined to religious institutions. The invention of the mechanical movable-type printing press in the mid-15th century by Johannes Gutenberg in Mainz, Germany, changed this forever. Gutenberg''s press combined several existing technologies—movable metal type, oil-based ink, and a screw press adapted from winemaking—to create a faster, more efficient method for reproducing texts. The first major book printed with this technology was the Gutenberg Bible, which marked the beginning of mass communication in Europe. The printing press enabled the rapid dissemination of knowledge, ideas, and information, leading to increased literacy rates and cultural exchange. It played a critical role in major historical movements, such as the Renaissance and the Protestant Reformation. By making books more affordable and widely available, it allowed new ideas to spread far beyond traditional centers of learning. The Reformation, for example, was fueled by printed pamphlets and religious tracts that challenged the authority of the Catholic Church. The press also contributed to the growth of vernacular literature, as authors began writing in local languages instead of Latin, making texts accessible to a broader audience. Furthermore, the printing press influenced the development of science by facilitating the distribution of research and discoveries. Scholars like Copernicus, Galileo, and Newton could publish their findings, leading to collaborative advancements across Europe. This democratization of knowledge was instrumental in shaping modern scientific thought. In summary, the printing press revolutionized the way people accessed and shared information. It broke the monopoly of knowledge held by the elite and religious institutions, paving the way for widespread education and intellectual growth. Its legacy can still be seen today in the way we consume and disseminate information through books, newspapers, and digital media.', 3, 'lecture', 300),

(1, 'listening', 'Environmental Science Lecture: Urban Green Spaces', 'Today we''ll examine the importance of urban green spaces—parks, community gardens, and greenways—and their impact on public health. Urban areas have expanded rapidly in recent decades, often at the expense of natural landscapes. This trend has contributed to environmental issues such as air and noise pollution, urban heat islands, and reduced biodiversity. The introduction of green spaces into cities serves several purposes: first, they act as ''lungs'' by absorbing carbon dioxide and releasing oxygen, which improves air quality. Trees and vegetation also filter airborne pollutants, reducing respiratory problems among residents. Second, green spaces help mitigate urban heat. Concrete and asphalt absorb and retain heat, making cities hotter than surrounding areas. Parks and tree canopy shade cool the environment, lowering ambient temperatures by several degrees on hot days. Third, these spaces offer psychological benefits—access to nature within urban settings reduces stress, improves mood, and encourages social interaction, which supports mental well-being. Studies have shown that people living near parks report lower levels of anxiety and depression. Fourth, urban green areas promote physical activity. Walking paths, playgrounds, and sports facilities encourage exercise, which helps combat obesity, heart disease, and diabetes. Fifth, green infrastructure supports urban biodiversity by providing habitats for birds, insects, and small mammals. Pollinators like bees and butterflies rely on these corridors to thrive. Sixth, green spaces help manage stormwater. Vegetation absorbs rainwater and reduces runoff into sewer systems, lowering flood risk. However, challenges remain. Poor urban planning, lack of funding, and competing land use priorities can limit green space availability. Equitable access is also a concern—low-income neighborhoods often have fewer parks. To address this, city planners and public health officials are collaborating to integrate green space into new developments and retrofit existing ones. Initiatives include planting street trees, converting vacant lots into community gardens, and creating green rooftops. In conclusion, urban green spaces play a multifaceted role in public health—from environmental cleanup and climate regulation to mental health support and community-building. Investing in these areas helps create healthier, more sustainable and equitable cities.', 4, 'lecture', 300),

(1, 'listening', 'Biology Lecture: The Science of Sleep', 'In this lecture, we''ll delve into the science of sleep—why it''s essential, how it works, and the consequences of sleep deprivation. Sleep is not a passive state of rest; it''s a complex biological process organized into distinct stages. The first stage is light sleep, which acts as a transition between wakefulness and deeper sleep. Next comes slow-wave sleep, characterized by deep, restorative rest, crucial for physical recovery and memory consolidation. The third type is rapid eye movement, or REM sleep, when most dreaming occurs. REM sleep is important for emotional regulation and cognitive processing. Adults typically cycle through these stages multiple times each night, with total sleep needs averaging around seven to nine hours. Sleep is regulated by biological clocks—our circadian rhythm—synchronized by external cues like light and temperature. This rhythm is controlled by the suprachiasmatic nucleus in the brain, which coordinates hormone release, including melatonin, to induce sleep. Lack of adequate sleep has serious consequences: daytime sleepiness, impaired attention, mood disturbances, weakened immune function, increased risk of cardiovascular disease, and reduced metabolic health. Chronic sleep deprivation has also been linked to obesity, diabetes, and mental health disorders such as anxiety and depression. Researchers recommend sleep hygiene practices to improve sleep quality: maintaining a consistent sleep schedule, creating a relaxing bedtime routine, avoiding screens before bed, and ensuring a comfortable environment—cool, dark, and quiet. Certain lifestyle factors also affect sleep: caffeine and alcohol can disrupt sleep architecture, while regular daytime exercise can promote it. In recent years, wearable devices and apps have allowed individuals to monitor their sleep patterns, offering insights into duration and quality. However, the accuracy varies, so professional medical assessment may still be necessary for sleep disorders like insomnia, sleep apnea, and narcolepsy. In summary, sleep is a vital, active process that supports physical, cognitive, and emotional health. Understanding and optimizing our sleep can lead to better overall well-being and productivity.', 5, 'lecture', 300),

(1, 'listening', 'Student-Professor Conversation: Biology Midterm', 'Listen to a conversation between a student and professor about a biology midterm exam.', 6, 'conversation', 180),

(1, 'listening', 'Student-Professor Conversation: Marine Biology Research Project', 'Listen to a conversation between a student and professor about a marine biology research project.', 7, 'conversation', 180);

-- Insert listening questions for History Lecture: The Printing Press (T1L1)
INSERT INTO public.test_questions (test_id, passage_id, section_type, question_number, question_type, question_text, options, correct_answer) VALUES 

(1, (SELECT id FROM public.test_passages WHERE title = 'History Lecture: The Printing Press' AND test_id = 1), 'listening', 32, 'Gist-Content', 'What is the lecture mainly about?', '["Religious reforms in medieval Europe", "The invention and societal impact of the printing press", "Handwritten manuscripts in monasteries", "The development of modern newspapers"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'History Lecture: The Printing Press' AND test_id = 1), 'listening', 33, 'Detail', 'Who invented the mechanical movable-type printing press?', '["Leonardo da Vinci", "Johannes Gutenberg", "Isaac Newton", "Martin Luther"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'History Lecture: The Printing Press' AND test_id = 1), 'listening', 34, 'Attitude', 'What is the professor''s attitude toward the printing press?', '["Critical", "Dismissive", "Appreciative of its significance", "Neutral"]', '"2"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'History Lecture: The Printing Press' AND test_id = 1), 'listening', 35, 'Organization', 'Why does the professor mention the Gutenberg Bible?', '["To illustrate a common book people read", "To show the printing press''s capability for mass production", "To discuss religious controversies", "To describe early illustrated manuscripts"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'History Lecture: The Printing Press' AND test_id = 1), 'listening', 36, 'Connecting Content', 'What was one result of the printing press''s introduction?', '["A decline in literacy", "Faster manuscript copying by monks", "The rapid spread of ideas fueling the Renaissance", "Fewer books being printed"]', '"2"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'History Lecture: The Printing Press' AND test_id = 1), 'listening', 37, 'Inference', 'What can be inferred about the role of the printing press in science?', '["It hindered research", "It helped spread new discoveries", "It replaced scientists with scribes", "It limited debate"]', '"1"'),

-- Insert listening questions for Environmental Science Lecture: Urban Green Spaces (T1L2)
(1, (SELECT id FROM public.test_passages WHERE title = 'Environmental Science Lecture: Urban Green Spaces' AND test_id = 1), 'listening', 38, 'Gist-Content', 'What is the lecture mainly about?', '["Wildlife conservation in rural areas", "The role of urban green spaces in public health", "Industrial development in cities", "Traffic congestion solutions"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Environmental Science Lecture: Urban Green Spaces' AND test_id = 1), 'listening', 39, 'Detail', 'Which benefit do urban green spaces provide?', '["Increase in property taxes", "Reduction of air pollution", "Replacement for public transportation", "Expansion of urban sprawl"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Environmental Science Lecture: Urban Green Spaces' AND test_id = 1), 'listening', 40, 'Attitude', 'What is the professor''s attitude toward green spaces?', '["Dismissive", "Cautiously positive", "Supportive and encouraging", "Neutral"]', '"2"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Environmental Science Lecture: Urban Green Spaces' AND test_id = 1), 'listening', 41, 'Organization', 'Why does the professor mention stormwater management?', '["To show a negative aspect of green spaces", "To demonstrate an environmental benefit", "To discourage green rooftops", "To discuss city planning errors"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Environmental Science Lecture: Urban Green Spaces' AND test_id = 1), 'listening', 42, 'Connecting Content', 'What effect do green areas have on mental health?', '["They increase isolation", "They raise anxiety", "They reduce stress and depression", "They cause allergies"]', '"2"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Environmental Science Lecture: Urban Green Spaces' AND test_id = 1), 'listening', 43, 'Inference', 'What can be inferred about low-income neighborhoods?', '["They have more green spaces", "They often lack adequate parks", "They do not benefit from parks", "They are untouched by urban issues"]', '"1"'),

-- Insert listening questions for Biology Lecture: The Science of Sleep (T1L3)
(1, (SELECT id FROM public.test_passages WHERE title = 'Biology Lecture: The Science of Sleep' AND test_id = 1), 'listening', 44, 'Gist-Content', 'What is the lecture mainly about?', '["The benefits of exercise", "The biological importance of sleep", "The history of medical devices", "The taste of sleeping pills"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Biology Lecture: The Science of Sleep' AND test_id = 1), 'listening', 45, 'Detail', 'Which stage of sleep involves dreaming?', '["Light sleep", "Slow-wave sleep", "REM sleep", "Deep sleep"]', '"2"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Biology Lecture: The Science of Sleep' AND test_id = 1), 'listening', 46, 'Attitude', 'What is the professor''s attitude toward sleep hygiene?', '["Neutral", "Supportive of its benefits", "Skeptical", "Discouraging"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Biology Lecture: The Science of Sleep' AND test_id = 1), 'listening', 47, 'Organization', 'Why does the professor discuss wearable devices?', '["To promote unhealthy habits", "To describe tools for sleep monitoring", "To argue against medical assessments", "To sell products"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Biology Lecture: The Science of Sleep' AND test_id = 1), 'listening', 48, 'Connecting Content', 'Which health risk is linked to chronic sleep deprivation?', '["Improved eyesight", "Cardiovascular disease", "Increased IQ", "Heightened immunity"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Biology Lecture: The Science of Sleep' AND test_id = 1), 'listening', 49, 'Inference', 'What can be inferred about screen use before bedtime?', '["It promotes better sleep", "It disrupts natural sleep patterns", "It has no effect", "It accelerates REM sleep"]', '"1"'),

-- Insert listening questions for Student-Professor Conversation: Biology Midterm (T1C1)
(1, (SELECT id FROM public.test_passages WHERE title = 'Student-Professor Conversation: Biology Midterm' AND test_id = 1), 'listening', 50, 'Gist-Purpose', 'Why does the student meet with the professor?', '["To ask about the midterm exam format", "To request a course drop", "To discuss a research project", "To complain about grades"]', '"0"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Student-Professor Conversation: Biology Midterm' AND test_id = 1), 'listening', 51, 'Detail', 'How many short-answer essays are on the exam?', '["One", "Two", "Three", "None"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Student-Professor Conversation: Biology Midterm' AND test_id = 1), 'listening', 52, 'Attitude', 'What is the professor''s attitude toward the student''s questions?', '["Annoyed", "Supportive", "Indifferent", "Dismissive"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Student-Professor Conversation: Biology Midterm' AND test_id = 1), 'listening', 53, 'Function', 'What does the professor mean by "Only procedural questions"?', '["You can ask clarifications about exam rules", "You can ask about essay content", "You can ask for hints", "You can ask about class attendance"]', '"0"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Student-Professor Conversation: Biology Midterm' AND test_id = 1), 'listening', 54, 'Organization', 'Why does the professor explain the weight of the midterm grade?', '["To scare the student", "To inform about the exam''s importance", "To discuss final exams only", "To talk about attendance"]', '"1"'),

-- Insert listening questions for Student-Professor Conversation: Marine Biology Research Project (T1C2)
(1, (SELECT id FROM public.test_passages WHERE title = 'Student-Professor Conversation: Marine Biology Research Project' AND test_id = 1), 'listening', 55, 'Gist-Purpose', 'Why does the student meet with the professor?', '["To discuss the research project guidelines", "To complain about homework", "To request an extension", "To ask for a letter of recommendation"]', '"0"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Student-Professor Conversation: Marine Biology Research Project' AND test_id = 1), 'listening', 56, 'Detail', 'How many peer-reviewed articles are required?', '["At least five", "At least eight", "At least ten", "No academic sources needed"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Student-Professor Conversation: Marine Biology Research Project' AND test_id = 1), 'listening', 57, 'Attitude', 'What is the professor''s attitude toward student questions?', '["Dismissive", "Supportive", "Critical", "Indifferent"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Student-Professor Conversation: Marine Biology Research Project' AND test_id = 1), 'listening', 58, 'Function', 'What does the professor mean by "feel free to show me a draft during office hours"?', '["You should present today", "You are allowed to get feedback before finalizing", "You must print your draft now", "You can skip work"]', '"1"'),

(1, (SELECT id FROM public.test_passages WHERE title = 'Student-Professor Conversation: Marine Biology Research Project' AND test_id = 1), 'listening', 59, 'Organization', 'Why does the professor mention peer feedback sessions?', '["To introduce a collaborative phase", "To schedule presentations", "To assign grades early", "To discuss attendance policy"]', '"0"');
