// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdirwxqcamngvsubjbdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkaXJ3eHFjYW1uZ3ZzdWJqYmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDgyMTUsImV4cCI6MjA2NjAyNDIxNX0.GGOdVznOcqQluLhH5J8HqPmVZRZNIDxU9YtoqfAKwZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);